security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
            cost: 12
    providers:
        user_db:
            entity: { class: App\Entity\User, property: id }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/(?!api)
        api:
            pattern:   ^/(api(?!/(doc|login)))
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            provider: user_db

    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }
